# Generated by Django 4.2 on 2026-05-10 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IrrigationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ObservationYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(max_length=30)),
                ('recommendation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.croptype')),
                ('irrigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.irrigationmethod')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.region')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.observationyear')),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentalSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wind_speed_kmh', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('wind_gust_kmh', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('wind_direction', models.CharField(default='NE', max_length=10)),
                ('rainfall_mm', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('rainfall_delta_percent', models.IntegerField(default=0)),
                ('ph_level', models.DecimalField(decimal_places=1, default=7.0, max_digits=3)),
                ('npk_index', models.CharField(default='Med-High', max_length=20)),
                ('temperature_c', models.DecimalField(decimal_places=1, default=25, max_digits=4)),
                ('humidity_percent', models.IntegerField(default=60)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.region')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.observationyear')),
            ],
            options={
                'unique_together': {('region', 'year')},
            },
        ),
    ]
