# Generated by Django 4.2 on 2026-05-23 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('Excel', 'Excel File'), ('API', 'API Integration'), ('Manual', 'Manual Entry')], max_length=20)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('metric_type', models.CharField(help_text='Type of metric imported (Soil, Climate, etc.)', max_length=50)),
                ('records_imported', models.IntegerField(default=0)),
                ('import_date', models.DateTimeField(auto_now_add=True)),
                ('imported_by', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed'), ('Partial', 'Partial')], default='Success', max_length=20)),
            ],
            options={
                'ordering': ['-import_date'],
            },
        ),
        migrations.CreateModel(
            name='ClimateMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_date', models.DateField()),
                ('rainfall_mm', models.DecimalField(decimal_places=1, help_text='Rainfall amount (mm)', max_digits=6)),
                ('seasonal_rainfall_variability', models.CharField(blank=True, help_text='Seasonal variability classification', max_length=50)),
                ('temperature_max_c', models.DecimalField(decimal_places=1, help_text='Daily max temperature (°C)', max_digits=4)),
                ('temperature_min_c', models.DecimalField(decimal_places=1, help_text='Daily min temperature (°C)', max_digits=4)),
                ('temperature_mean_c', models.DecimalField(decimal_places=1, help_text='Daily mean temperature (°C)', max_digits=4)),
                ('relative_humidity_percent', models.IntegerField(help_text='Relative humidity (%)')),
                ('wind_speed_ms', models.DecimalField(decimal_places=2, help_text='Wind speed (m/s at 2m height)', max_digits=4)),
                ('solar_radiation_mjm2day', models.DecimalField(decimal_places=2, help_text='Solar radiation (MJ/m²/day)', max_digits=6)),
                ('evapotranspiration_et0_mmday', models.DecimalField(decimal_places=2, help_text='Reference ET₀ (mm/day)', max_digits=5)),
                ('evapotranspiration_etc_mmday', models.DecimalField(blank=True, decimal_places=2, help_text='Crop ET (mm/day)', max_digits=5, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climate_metrics', to='dashboard.region')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.observationyear')),
            ],
            options={
                'ordering': ['-measurement_date'],
            },
        ),
        migrations.CreateModel(
            name='AgriculturalMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_date', models.DateField()),
                ('growth_stage', models.CharField(choices=[('Germination', 'Germination'), ('Vegetative', 'Vegetative'), ('Flowering', 'Flowering'), ('Grain Filling', 'Grain Filling'), ('Maturity', 'Maturity')], max_length=20)),
                ('crop_coefficient_kc', models.DecimalField(decimal_places=2, help_text='Crop coefficient (Kc)', max_digits=4)),
                ('crop_water_requirement_mmday', models.DecimalField(decimal_places=2, help_text='CWR (mm/day)', max_digits=5)),
                ('yield_reduction_factor', models.DecimalField(decimal_places=3, help_text='Sensitivity to water stress (0-1)', max_digits=5)),
                ('irrigation_efficiency_percent', models.IntegerField(help_text='Irrigation efficiency (%)')),
                ('water_applied_mm', models.DecimalField(decimal_places=2, help_text='Water applied (mm)', max_digits=6)),
                ('leaf_temperature_c', models.DecimalField(blank=True, decimal_places=1, help_text='Leaf temperature (°C)', max_digits=4, null=True)),
                ('stomatal_conductance', models.DecimalField(blank=True, decimal_places=3, help_text='Stomatal conductance (mol/m²/s)', max_digits=6, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.croptype')),
                ('irrigation_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.irrigationmethod')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agricultural_metrics', to='dashboard.region')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.observationyear')),
            ],
            options={
                'ordering': ['-measurement_date'],
            },
        ),
        migrations.CreateModel(
            name='SoilMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_date', models.DateField(auto_now_add=True)),
                ('moisture_content_percent', models.DecimalField(decimal_places=2, help_text='Volumetric water content (%)', max_digits=5)),
                ('sand_ratio', models.DecimalField(blank=True, decimal_places=2, help_text='Sand ratio (%)', max_digits=5, null=True)),
                ('clay_ratio', models.DecimalField(blank=True, decimal_places=2, help_text='Clay ratio (%)', max_digits=5, null=True)),
                ('silt_ratio', models.DecimalField(blank=True, decimal_places=2, help_text='Silt ratio (%)', max_digits=5, null=True)),
                ('root_zone_depth_mm', models.IntegerField(help_text='Available water holding capacity (mm)')),
                ('organic_matter_percent', models.DecimalField(decimal_places=2, help_text='Organic matter content (%)', max_digits=5)),
                ('infiltration_rate_mmhr', models.DecimalField(decimal_places=2, help_text='Infiltration rate (mm/hr)', max_digits=6)),
                ('field_capacity_percent', models.DecimalField(decimal_places=2, help_text='Field capacity threshold (%)', max_digits=5)),
                ('wilting_point_percent', models.DecimalField(decimal_places=2, help_text='Wilting point threshold (%)', max_digits=5)),
                ('salinity_ece_dsm', models.DecimalField(decimal_places=3, help_text='Electrical conductivity (dS/m)', max_digits=5)),
                ('ph_level', models.DecimalField(decimal_places=1, help_text='Soil pH level', max_digits=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_metrics', to='dashboard.region')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.observationyear')),
            ],
            options={
                'ordering': ['-measurement_date'],
                'unique_together': {('region', 'year', 'measurement_date')},
            },
        ),
        migrations.CreateModel(
            name='RemoteSensingMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_date', models.DateField()),
                ('ndvi', models.DecimalField(decimal_places=3, help_text='NDVI (-1 to 1, vegetation health)', max_digits=4)),
                ('ndwi', models.DecimalField(blank=True, decimal_places=3, help_text='NDWI (water content in vegetation)', max_digits=4, null=True)),
                ('land_surface_temperature_c', models.DecimalField(blank=True, decimal_places=2, help_text='LST (°C)', max_digits=5, null=True)),
                ('satellite_soil_moisture_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Soil moisture from satellite (%)', max_digits=5, null=True)),
                ('satellite_source', models.CharField(blank=True, choices=[('SMAP', 'SMAP'), ('Sentinel-1', 'Sentinel-1'), ('MODIS', 'MODIS'), ('Landsat', 'Landsat')], max_length=50)),
                ('vegetation_condition_index', models.DecimalField(blank=True, decimal_places=2, help_text='VCI (% of normal)', max_digits=5, null=True)),
                ('evapotranspiration_sebal_mmday', models.DecimalField(blank=True, decimal_places=2, help_text='ET from SEBAL/METRIC (mm/day)', max_digits=5, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_sensing', to='dashboard.region')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.observationyear')),
            ],
            options={
                'ordering': ['-measurement_date'],
                'unique_together': {('region', 'year', 'measurement_date')},
            },
        ),
        migrations.CreateModel(
            name='HydrologyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_date', models.DateField()),
                ('precipitation_mm', models.DecimalField(decimal_places=1, help_text='Precipitation (mm)', max_digits=6)),
                ('evapotranspiration_mm', models.DecimalField(decimal_places=1, help_text='Evapotranspiration (mm)', max_digits=6)),
                ('groundwater_depth_m', models.DecimalField(decimal_places=2, help_text='Groundwater depth (m)', max_digits=6)),
                ('runoff_mm', models.DecimalField(decimal_places=1, help_text='Runoff (mm)', max_digits=6)),
                ('river_flow_m3s', models.DecimalField(blank=True, decimal_places=2, help_text='River flow (m³/s)', max_digits=10, null=True)),
                ('reservoir_storage_m3', models.DecimalField(blank=True, decimal_places=0, help_text='Reservoir storage (m³)', max_digits=15, null=True)),
                ('irrigation_supply_available_m3', models.DecimalField(blank=True, decimal_places=0, help_text='Available irrigation supply (m³)', max_digits=15, null=True)),
                ('soil_water_deficit_index_mm', models.DecimalField(decimal_places=2, help_text='Soil water deficit (ETc - available water)', max_digits=6)),
                ('water_balance_percent', models.DecimalField(decimal_places=2, help_text='Water balance (supply - demand %)', max_digits=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hydrology_metrics', to='dashboard.region')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.observationyear')),
            ],
            options={
                'ordering': ['-measurement_date'],
                'unique_together': {('region', 'year', 'measurement_date')},
            },
        ),
        migrations.CreateModel(
            name='DroughtIndices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_date', models.DateField()),
                ('spi_1month', models.DecimalField(blank=True, decimal_places=2, help_text='SPI 1-month', max_digits=5, null=True)),
                ('spi_3month', models.DecimalField(blank=True, decimal_places=2, help_text='SPI 3-month', max_digits=5, null=True)),
                ('spi_12month', models.DecimalField(blank=True, decimal_places=2, help_text='SPI 12-month', max_digits=5, null=True)),
                ('spei_1month', models.DecimalField(blank=True, decimal_places=2, help_text='SPEI 1-month', max_digits=5, null=True)),
                ('spei_3month', models.DecimalField(blank=True, decimal_places=2, help_text='SPEI 3-month', max_digits=5, null=True)),
                ('spei_12month', models.DecimalField(blank=True, decimal_places=2, help_text='SPEI 12-month', max_digits=5, null=True)),
                ('pdsi_value', models.DecimalField(blank=True, decimal_places=2, help_text='PDSI value', max_digits=5, null=True)),
                ('drought_severity_class', models.CharField(choices=[('None', 'No Drought'), ('Abnormally Dry', 'Abnormally Dry'), ('Moderate Drought', 'Moderate Drought'), ('Severe Drought', 'Severe Drought'), ('Extreme Drought', 'Extreme Drought')], default='None', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drought_indices', to='dashboard.region')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.observationyear')),
            ],
            options={
                'ordering': ['-measurement_date'],
                'unique_together': {('region', 'year', 'measurement_date')},
            },
        ),
        migrations.AddIndex(
            model_name='climatemetrics',
            index=models.Index(fields=['region', 'measurement_date'], name='dashboard_c_region__d9ee8b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='climatemetrics',
            unique_together={('region', 'year', 'measurement_date')},
        ),
        migrations.AddIndex(
            model_name='agriculturalmetrics',
            index=models.Index(fields=['region', 'crop', 'measurement_date'], name='dashboard_a_region__19ae2b_idx'),
        ),
    ]
