# Generated by Django 4.2 on 2026-05-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_dataimportlog_climatemetrics_agriculturalmetrics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataimportlog',
            name='error_details',
            field=models.TextField(blank=True, help_text='JSON details of import errors', null=True),
        ),
    ]
