# Generated by Django 4.2 on 2026-05-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_dataimportlog_error_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agriculturalmetrics',
            name='crop_coefficient_kc',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Crop coefficient (Kc)', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='agriculturalmetrics',
            name='crop_water_requirement_mmday',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='CWR (mm/day)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='agriculturalmetrics',
            name='irrigation_efficiency_percent',
            field=models.IntegerField(blank=True, help_text='Irrigation efficiency (%)', null=True),
        ),
        migrations.AlterField(
            model_name='agriculturalmetrics',
            name='water_applied_mm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Water applied (mm)', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='agriculturalmetrics',
            name='yield_reduction_factor',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Sensitivity to water stress (0-1)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='climatemetrics',
            name='evapotranspiration_et0_mmday',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Reference ET₀ (mm/day)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='climatemetrics',
            name='rainfall_mm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Rainfall amount (mm)', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='climatemetrics',
            name='relative_humidity_percent',
            field=models.IntegerField(blank=True, help_text='Relative humidity (%)', null=True),
        ),
        migrations.AlterField(
            model_name='climatemetrics',
            name='solar_radiation_mjm2day',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Solar radiation (MJ/m²/day)', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='climatemetrics',
            name='temperature_max_c',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Daily max temperature (°C)', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='climatemetrics',
            name='temperature_mean_c',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Daily mean temperature (°C)', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='climatemetrics',
            name='temperature_min_c',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Daily min temperature (°C)', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='climatemetrics',
            name='wind_speed_ms',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Wind speed (m/s at 2m height)', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='hydrologymetrics',
            name='evapotranspiration_mm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Evapotranspiration (mm)', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='hydrologymetrics',
            name='groundwater_depth_m',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Groundwater depth (m)', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='hydrologymetrics',
            name='precipitation_mm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Precipitation (mm)', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='hydrologymetrics',
            name='runoff_mm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Runoff (mm)', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='hydrologymetrics',
            name='soil_water_deficit_index_mm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Soil water deficit (ETc - available water)', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='hydrologymetrics',
            name='water_balance_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Water balance (supply - demand %)', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='remotesensingmetrics',
            name='ndvi',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='NDVI (-1 to 1, vegetation health)', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='soilmetrics',
            name='field_capacity_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Field capacity threshold (%)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='soilmetrics',
            name='infiltration_rate_mmhr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Infiltration rate (mm/hr)', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='soilmetrics',
            name='moisture_content_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Volumetric water content (%)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='soilmetrics',
            name='organic_matter_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Organic matter content (%)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='soilmetrics',
            name='ph_level',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Soil pH level', max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='soilmetrics',
            name='root_zone_depth_mm',
            field=models.IntegerField(blank=True, help_text='Available water holding capacity (mm)', null=True),
        ),
        migrations.AlterField(
            model_name='soilmetrics',
            name='salinity_ece_dsm',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Electrical conductivity (dS/m)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='soilmetrics',
            name='wilting_point_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Wilting point threshold (%)', max_digits=5, null=True),
        ),
    ]
