# Generated by Django 4.2 on 2026-05-28 10:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_agriculturalmetrics_crop_coefficient_kc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DroughtPrediction',
            fields=[
                ('id', models.BigAutoField(db_column='prediction_id', primary_key=True, serialize=False)),
                ('prediction_date', models.DateField(auto_now_add=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('model_version', models.CharField(default='v1', max_length=50)),
                ('current_risk_score', models.DecimalField(decimal_places=1, max_digits=5)),
                ('risk_7day', models.DecimalField(decimal_places=1, max_digits=5)),
                ('risk_30day', models.DecimalField(decimal_places=1, max_digits=5)),
                ('soil_moisture_today_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('soil_moisture_7day_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('soil_moisture_30day_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('drivers', models.JSONField(blank=True, default=dict)),
                ('explanation', models.TextField(blank=True)),
                ('source_window_days', models.IntegerField(default=30)),
            ],
            options={
                'db_table': 'drought_predictions',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='agriculturalmetrics',
            new_name='agricultura_region__35beaa_idx',
            old_name='dashboard_a_region__19ae2b_idx',
        ),
        migrations.RenameIndex(
            model_name='climatemetrics',
            new_name='climate_met_region__5b59ae_idx',
            old_name='dashboard_c_region__d9ee8b_idx',
        ),
        migrations.AddField(
            model_name='environmentalsnapshot',
            name='time',
            field=models.DateTimeField(auto_now_add=True, db_column='time', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agriculturalmetrics',
            name='id',
            field=models.BigAutoField(db_column='metric_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='agriculturalmetrics',
            name='irrigation_method',
            field=models.ForeignKey(blank=True, db_column='irrigation_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.irrigationmethod'),
        ),
        migrations.AlterField(
            model_name='agriculturalmetrics',
            name='measurement_date',
            field=models.DateField(db_column='time'),
        ),
        migrations.AlterField(
            model_name='climatemetrics',
            name='id',
            field=models.BigAutoField(db_column='metric_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='climatemetrics',
            name='measurement_date',
            field=models.DateField(db_column='time'),
        ),
        migrations.AlterField(
            model_name='croptype',
            name='id',
            field=models.BigAutoField(db_column='crop_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dataimportlog',
            name='id',
            field=models.BigAutoField(db_column='log_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='droughtindices',
            name='id',
            field=models.BigAutoField(db_column='metric_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='droughtindices',
            name='measurement_date',
            field=models.DateField(db_column='time'),
        ),
        migrations.AlterField(
            model_name='environmentalsnapshot',
            name='id',
            field=models.BigAutoField(db_column='snapshot_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hydrologymetrics',
            name='id',
            field=models.BigAutoField(db_column='metric_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hydrologymetrics',
            name='measurement_date',
            field=models.DateField(db_column='time'),
        ),
        migrations.AlterField(
            model_name='irrigationmethod',
            name='id',
            field=models.BigAutoField(db_column='irrigation_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='observationyear',
            name='id',
            field=models.BigAutoField(db_column='year_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='region',
            name='id',
            field=models.BigAutoField(db_column='region_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='remotesensingmetrics',
            name='id',
            field=models.BigAutoField(db_column='metric_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='remotesensingmetrics',
            name='measurement_date',
            field=models.DateField(db_column='time'),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='id',
            field=models.BigAutoField(db_column='assessment_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='soilmetrics',
            name='id',
            field=models.BigAutoField(db_column='metric_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='soilmetrics',
            name='measurement_date',
            field=models.DateField(db_column='time'),
        ),
        migrations.AlterModelTable(
            name='agriculturalmetrics',
            table='agricultural_metrics',
        ),
        migrations.AlterModelTable(
            name='climatemetrics',
            table='climate_metrics',
        ),
        migrations.AlterModelTable(
            name='croptype',
            table='crop_types',
        ),
        migrations.AlterModelTable(
            name='dataimportlog',
            table='data_import_logs',
        ),
        migrations.AlterModelTable(
            name='droughtindices',
            table='drought_indices',
        ),
        migrations.AlterModelTable(
            name='environmentalsnapshot',
            table='environmental_snapshots',
        ),
        migrations.AlterModelTable(
            name='hydrologymetrics',
            table='hydrology_metrics',
        ),
        migrations.AlterModelTable(
            name='irrigationmethod',
            table='irrigation_methods',
        ),
        migrations.AlterModelTable(
            name='observationyear',
            table='observation_years',
        ),
        migrations.AlterModelTable(
            name='region',
            table='regions',
        ),
        migrations.AlterModelTable(
            name='remotesensingmetrics',
            table='remote_sensing_metrics',
        ),
        migrations.AlterModelTable(
            name='riskassessment',
            table='risk_assessments',
        ),
        migrations.AlterModelTable(
            name='soilmetrics',
            table='soil_metrics',
        ),
        migrations.AddField(
            model_name='droughtprediction',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drought_predictions', to='dashboard.region'),
        ),
        migrations.AddField(
            model_name='droughtprediction',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.observationyear'),
        ),
        migrations.AddIndex(
            model_name='droughtprediction',
            index=models.Index(fields=['region', 'year', '-generated_at'], name='drought_pre_region__00a34e_idx'),
        ),
    ]
