# Generated by Django 4.2 on 2026-06-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_agriculturalmetrics_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('subadmin', 'Subadmin'), ('viewer', 'Viewer')], default='viewer', max_length=20),
        ),
    ]
