# Generated by Django 4.2 on 2026-06-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_userprofile_role'),
    ]

    operations = [
        # Metric model fields — all new columns
        migrations.AddField(
            model_name='agriculturalmetrics',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='agriculturalmetrics',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='climatemetrics',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='climatemetrics',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='droughtindices',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='droughtindices',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='hydrologymetrics',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='hydrologymetrics',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='remotesensingmetrics',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='remotesensingmetrics',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='soilmetrics',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='soilmetrics',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        # Region fields — only radius_km is new in DB; others already exist
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='region',
                    name='area_km2',
                    field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                migrations.AddField(
                    model_name='region',
                    name='country',
                    field=models.CharField(blank=True, max_length=100, null=True),
                ),
                migrations.AddField(
                    model_name='region',
                    name='description',
                    field=models.TextField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='region',
                    name='elevation_m',
                    field=models.IntegerField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='region',
                    name='latitude',
                    field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
                ),
                migrations.AddField(
                    model_name='region',
                    name='longitude',
                    field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
                ),
            ],
            database_operations=[],
        ),
        migrations.AddField(
            model_name='region',
            name='radius_km',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=8),
        ),
    ]
