# Generated by Django 4.2 on 2026-07-07 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_seed_region_coordinates'),
        ('dashboard', '0010_region_add_missing_fields'),
    ]

    operations = [
    ]
