# Generated by Django 4.2 on 2026-07-07 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0011_merge_20260707_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(db_column='sensor_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('sensor_type', models.CharField(choices=[('aws', 'Weather Station'), ('soil', 'Soil Moisture'), ('water', 'Water Level'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('coverage_radius_km', models.DecimalField(decimal_places=2, default=10.0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.region')),
            ],
            options={
                'db_table': 'sensors',
            },
        ),
    ]
